apiVersion: v1
kind: Service
metadata:
  name: lumina-providers-service
  namespace: lumina-ai
  labels:
    app: lumina-ai
    component: providers
spec:
  selector:
    app: lumina-ai
    component: providers
  ports:
    - port: 8001
      targetPort: 8001
      name: http
  type: ClusterIP
