apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumina-core-deployment
  namespace: lumina-ai
  labels:
    app: lumina-ai
    component: core
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lumina-ai
      component: core
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: lumina-ai
        component: core
    spec:
      containers:
      - name: lumina-core
        image: lumina-ai/core:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        envFrom:
        - configMapRef:
            name: lumina-ai-config
        - secretRef:
            name: lumina-ai-secrets
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: core-data
          mountPath: /app/data
      volumes:
      - name: core-data
        persistentVolumeClaim:
          claimName: core-data-pvc
