server:
  port: 8084

spring:
  application:
    name: learning-service
  datasource:
    url: jdbc:h2:mem:learningdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

lumina:
  collaboration:
    api:
      url: http://collaboration-service:8083/api/v1
  integration:
    api:
      url: http://integration-service:8082/api/v1
  security:
    jwt:
      secret: luminaAILearningServiceSecretKey
      expiration: 86400000 # 24 hours

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
    ai.lumina: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
