apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumina-memory-deployment
  namespace: lumina-ai
  labels:
    app: lumina-ai
    component: memory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lumina-ai
      component: memory
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: lumina-ai
        component: memory
    spec:
      containers:
      - name: lumina-memory
        image: lumina-ai/memory:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8002
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
        envFrom:
        - configMapRef:
            name: lumina-ai-config
        - secretRef:
            name: lumina-ai-secrets
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: memory-data
          mountPath: /app/data
      volumes:
      - name: memory-data
        persistentVolumeClaim:
          claimName: memory-data-pvc
