global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api-gateway"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    eureka_sd_configs:
      - server: http://discovery-service:8761/eureka
    relabel_configs:
      - source_labels: [__meta_eureka_app_name]
        regex: API-GATEWAY
        action: keep

  - job_name: "provider-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    eureka_sd_configs:
      - server: http://discovery-service:8761/eureka
    relabel_configs:
      - source_labels: [__meta_eureka_app_name]
        regex: PROVIDER-SERVICE
        action: keep

  - job_name: "streaming-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    eureka_sd_configs:
      - server: http://discovery-service:8761/eureka
    relabel_configs:
      - source_labels: [__meta_eureka_app_name]
        regex: STREAMING-SERVICE
        action: keep

  - job_name: "auth-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    eureka_sd_configs:
      - server: http://discovery-service:8761/eureka
    relabel_configs:
      - source_labels: [__meta_eureka_app_name]
        regex: AUTH-SERVICE
        action: keep

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
