spring:
  application:
    name: integration-service
  datasource:
    url: jdbc:postgresql://postgres:5432/lumina
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  cloud:
    discovery:
      enabled: true

server:
  port: 8085
  servlet:
    context-path: /

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    ai.lumina: INFO
    org.springframework: WARN
    org.hibernate: WARN

integration:
  security:
    secret-key: ${INTEGRATION_SECRET_KEY:lumina-integration-secret-key}
    token-validity: 86400
  monitoring:
    metrics-enabled: true
    logging-enabled: true
  adapters:
    connection-timeout: 5000
    read-timeout: 10000
    max-connections: 100
