spring:
  application:
    name: security-service
  datasource:
    url: jdbc:postgresql://localhost:5432/lumina_security
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:8080/auth/realms/lumina

server:
  port: 8085
  servlet:
    context-path: /

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always

security:
  access-control:
    default-policy: deny
    cache-ttl-seconds: 300
  audit:
    enabled: true
    log-retention-days: 90
    sensitive-operations:
      - authentication
      - authorization
      - data-access
  encryption:
    key-rotation-days: 90
    algorithm: AES-256-GCM
  privacy:
    differential-privacy:
      enabled: true
      default-epsilon: 0.1
    data-minimization:
      enabled: true
  ethical:
    bias-detection:
      enabled: true
    explainability:
      enabled: true
    human-oversight:
      default-level: HUMAN_ON_THE_LOOP
