apiVersion: v1
kind: Service
metadata:
  name: lumina-core-service
  namespace: lumina-ai
  labels:
    app: lumina-ai
    component: core
spec:
  selector:
    app: lumina-ai
    component: core
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  type: ClusterIP
