apiVersion: v1
kind: Service
metadata:
  name: lumina-security-service
  namespace: lumina-ai
  labels:
    app: lumina-ai
    component: security
spec:
  selector:
    app: lumina-ai
    component: security
  ports:
    - port: 8003
      targetPort: 8003
      name: http
  type: ClusterIP
