apiVersion: v1
kind: Service
metadata:
  name: lumina-web-service
  namespace: lumina-ai
  labels:
    app: lumina-ai
    component: web
spec:
  selector:
    app: lumina-ai
    component: web
  ports:
    - port: 80
      targetPort: 80
      name: http
  type: LoadBalancer
